page/page/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views

from blog import views
from blog.views import (
    home_page,
    article_page,
    category_page,
    create_article,
    add_comment,
    registration,
    user_login,
    article_search,
    about_page,
    single_post_page,
    pages_page,
    contact_page,
    author_page,
    profile,
    profile_view,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home_page, name="home_page"),
    path("blog/<slug:slug>/", article_page, name="article_page"),
    path("blog/category/<slug:category>/", category_page, name="category_page"),
    path("blog/author/<slug:author_name>/", author_page, name="author_page"),
    path("create/", create_article, name="create_article"),
    path("article/<int:article_id>/add_comment/", add_comment, name="add_comment"),
    path("article-like/<int:article_id>/", views.article_like, name="article_like"),
    path("registration/", registration, name="registration"),
    path('profile-view/', profile_view, name='profile-view'),
    path('profile-edit/', profile, name='profile'),
    path("login/", user_login, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("search/", article_search, name="article_search"),
    path("about/", about_page, name="about_page"),
    path("single_post/", single_post_page, name="single_post_page"),
    path("pages/", pages_page, name="pages_page"),
    path("contact/", contact_page, name="contact_page"),
    path("subscribe", views.subscribe, name="subscribe"),
    path("newsletter", views.newsletter, name="newsletter"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

page/blog/forms.py
from django import forms
from .models import Article, Profile
from django.forms import ModelForm, TextInput, Textarea, Select, FileInput
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from tinymce.widgets import TinyMCE


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ["title", "summary", "full_text", "category", "slug", "og_image"]
        widgets = {
            "title": TextInput(attrs={"class": "form-control", "placeholder": "Title"}),
            "summary": Textarea(
                attrs={"class": "form-control", "placeholder": "Summary"}
            ),
            "full_text": Textarea(
                attrs={"class": "form-control", "placeholder": "Full Text"}
            ),
            "category": Select(
                attrs={
                    "class": "form-control",
                }
            ),
            "slug": TextInput(attrs={"class": "form-control", "placeholder": "Slug"}),
            "og_image": FileInput(
                attrs={
                    "class": "form-control",
                }
            ),
        }


class CommentForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={"rows": 4, "cols": 50}))


class RegistrationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.pop("autofocus", None)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Name", required=True)


class ArticleSearchForm(forms.Form):
    query = forms.CharField(
        label="Search Articles",
        max_length=100,
        widget=forms.TextInput(attrs={"placeholder": "Search for articles..."}),
    )


class NewsletterForm(forms.Form):
    subject = forms.CharField()
    receivers = forms.CharField()
    message = forms.CharField(widget=TinyMCE(), label="Email content")


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')

        if User.objects.filter(username=username).exists():
            self.add_error('username', 'Username is already taken.')

        if User.objects.filter(email=email).exists():
            self.add_error('email', 'This email is already registered.')

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    telephone = forms.CharField(max_length=15, required=False)
    bio = forms.CharField(widget=forms.Textarea, required=False)
    location = forms.CharField(max_length=100, required=False)
    birth_date = forms.DateField(required=False)
    twitter_url = forms.URLField(required=False)
    facebook_url = forms.URLField(required=False)
    instagram_url = forms.URLField(required=False)
    youtube_url = forms.URLField(required=False)
    image = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'form-profile-image'}))


    class Meta:
        model = Profile
        fields = ['telephone', 'bio', 'location', 'birth_date', 'twitter_url', 'facebook_url', 'instagram_url', 'youtube_url', 'image']

page/blog/views.py
# Django modules
from django.contrib import messages
from django.contrib.auth import (
    login,
    logout,
    authenticate,
    get_user_model,
)
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator
from django.core.mail import EmailMessage
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.generic import DetailView

# Models & Forms from my project
from .models import Article, Comment, Profile, SubscribedUsers
from .decorators import user_is_superuser
from .forms import (
    ArticleForm,
    CommentForm,
    RegistrationForm,
    LoginForm,
    ArticleSearchForm,
    NewsletterForm,
    UserRegisterForm,
    UserUpdateForm,
    ProfileUpdateForm,
)


global_context = {
    "author_name": _("Andrii Dorokhov"),
}


def home_page(request):
    articles = Article.objects.all().order_by("-pubdate")
    context = global_context | {"articles": articles}
    page_number = request.GET.get("page", 1)
    items_per_page = 9
    paginated = Paginator(articles, items_per_page)
    try:
        page = paginated.page(page_number)
    except PageNotAnInteger:
        page = paginated.page(1)
    except EmptyPage:
        page = paginated.page(paginated.num_pages)

    specific_article = Article.objects.first()

    show_pagination = paginated.num_pages == 1
    return render(
        request,
        "home_page.html",
        {
            "page": page,
            "specific_article": specific_article,
            **context,
            "show_pagination": show_pagination,
        },
    )


def about_page(request):
    context = global_context
    return render(request, "about_page.html", context)


def single_post_page(request):
    context = global_context
    return render(request, "single_post_page.html", context)


def pages_page(request):
    context = global_context
    return render(request, "pages_page.html", context)


def contact_page(request):
    context = global_context
    return render(request, "contact_page.html", context)


def article_page(request, slug):
    article = Article.objects.get(slug=slug)
    comments = Comment.objects.filter(article=article)
    comment_form = CommentForm()
    article_is_liked = request.user in article.likes.all()
    number_of_likes = article.number_of_likes()
    context = global_context | {
        "article": article,
        "comments": comments,
        "comment_form": comment_form,
        "number_of_likes": number_of_likes,
        "article_is_liked": article_is_liked,
    }
    return render(request, "article_page.html", context)


def category_page(request, category):
    articles = Article.objects.filter(category=category)
    context = global_context | {"articles": articles, "category": category}
    return render(request, "category_page.html", context)

def author_page(request, author_name):
    articles = Article.objects.filter(author_name=author_name).order_by("-pubdate")
    context = global_context | {"articles": articles, "author": author_name}
    page_number = request.GET.get("page", 1)
    items_per_page = 6
    paginated = Paginator(articles, items_per_page)
    try:
        page = paginated.page(page_number)
    except PageNotAnInteger:
        page = paginated.page(1)
    except EmptyPage:
        page = paginated.page(paginated.num_pages)

    specific_article = Article.objects.first()

    show_pagination = paginated.num_pages == 1
    return render(
        request,
        "author_page.html",
        {
            "page": page,
            "specific_article": specific_article,
            **context,
            "show_pagination": show_pagination,
        },
    )

def create_article(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.author_name = request.user.username
            article.save()
            # article.likes.set([request.user.id])
            messages.success(request, _("Article has been created successfully."))

            return redirect("home_page")
        else:
            messages.error(request, _("Please correct the errors below."))
    else:
        form = ArticleForm()

    context = global_context | {"form": form}
    return render(request, "create_article.html", context)


def add_comment(request, article_id):
    article = get_object_or_404(Article, id=article_id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data["text"]
            Comment.objects.create(article=article, user=request.user, text=text)

    return redirect("article_page", slug=article.slug)


def article_like(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if article.likes.filter(id=request.user.id).exists():
        article.likes.remove(request.user)
    else:
        article.likes.add(request.user)

    return HttpResponseRedirect(reverse("article_page", args=[article.slug]))

def registration(request):
    global_context = {'show_link': False, "page_title": 'User registration form', "page_description": 'Here you can register on the website by entering your name, email address, and password. If the name or email address is already registered, you will be notified. Afterwards, you can create and fill out your profile.'}
    context = {}
    context.update(global_context)
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")

            if User.objects.filter(username=username).exists():
                messages.error(request, "This username is already taken.")
            elif User.objects.filter(email=email).exists():
                messages.error(request, "This mailbox is already registered.")
            else:
                user = form.save(commit=False)
                user.save()
                Profile.objects.create(user=user, email=email)
                raw_password = form.cleaned_data.get("password1")
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                return redirect("home_page")
    else:
        form = RegistrationForm()
    return render(request, "./partials/registration.html", {"form": form, **context})


def user_login(request):
    global_context = {'show_link': False, "page_title": 'User registration form', "page_description": 'Here you can enter your username and the password you provided during registration.'}
    context = {}
    context.update(global_context)
    if request.method == "POST":
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home_page")
    else:
        form = LoginForm()
    return render(request, "./partials/login.html", {"form": form, **context})


def article_search(request):
    search_form = ArticleSearchForm(request.GET)
    query = request.GET.get("query", "")

    articles = Article.objects.filter(Q(title__icontains=query) | Q(category__icontains=query) | Q(full_text__icontains=query))
    context = {
        "search_form": search_form,
        "articles": articles,
    }

    return render(request, "search_results.html", context)

class ArticleDetailView(DetailView):
    model = Article
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        article = get_object_or_404(Article, slug=self.kwargs["slug"])
        liked = False
        if article.likes.filter(id=self.request.user.id).exists():
            liked = True
        data["total_likes"] = article.total_likes()
        data["article_is_liked"] = liked
        return data

@login_required
def profile(request):
    global_context = {"show_link": False, "page_title": 'User profile edit', "page_description": "This is your profile page. Here you can edit your profile information."}
    user = request.user
    article_count = Article.objects.filter(author=user).count()
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        try:
            profile = request.user.profile
        except Profile.DoesNotExist:
            profile = None
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            if profile:
                p_form.save()
            else:
                new_profile = p_form.save(commit=False)
                new_profile.user = request.user
                new_profile.save()
            messages.success(request, 'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        try:
            profile = request.user.profile
        except Profile.DoesNotExist:
            profile = None
        p_form = ProfileUpdateForm(instance=profile)

    context = {
        'user': user,
        'article_count': article_count,
        'u_form': u_form,
        'p_form': p_form,
    }
    context.update(global_context)

    return render(request, 'partials/profile_edit.html', context)

@login_required
def profile_view(request):

page/blog/templates/partials/comment.html
{% load i18n %}
<div class="comments-section">
	<h2 class="comments-section-title">{% translate "Comments" %}</h2>
	<ul class="comments-list">
		{% for comment in comments %}
		<li class="comment-item">
			<span class="comment-username">{{ comment.user.username }}:</span>
			<span class="comment-text">{{ comment.text }}</span>
		</li>
		{% empty %}
		<li class="no-comments-message">{% translate "No comments yet." %}</li>
		{% endfor %}
	</ul>
	{% if user.is_authenticated %}
	<div class="comment-container">
		<form method="post" action="{% url 'add_comment' article.id %}">
			{% csrf_token %}
			<textarea name="text"></textarea>
			<button type="submit" class="add-comment-button">
				{% translate "Add Comment" %}
			</button>
		</form>
	</div>
	{% endif %}
</div>

page/blog/templates/partials/footer.html
{% load static %}
<footer class="footer-distributed">
	<div class="footer-wrapper">
		<section class="footer-section-1">
			<div class="footer-left">
				<p class="footer-company-about">About</p>
				<p class="footer-company-text">
					Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
					eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
					minim veniam
				</p>
				<p class="footer-email">
					<span>Email:</span
					><a href="mailto:dorokhov.andrii@gmail.com">info@jstemplate.net</a>
				</p>
				<p class="footer-phone"><span>Phone:</span>880 123 456 789</p>
			</div>

			<div class="footer-center">
				<div class="link-list">
					<h3 class="footer-links">Quick Link</h3>
					<ul>
						<li><a href="#" class="link-1">Home</a></li>
						<li><a href="#">About</a></li>
						<li><a href="#">Blog</a></li>
						<li><a href="#">Archived</a></li>
						<li><a href="#">Author</a></li>
						<li><a href="#">Contact</a></li>
					</ul>
				</div>

				<div class="category-list">
					<h3 class="footer-links">Popular Category</h3>
					<ul>
						<li>
							<a href="{% url 'category_page' 'Lifestyle' %}">Lifestyle</a>
						</li>
						<li>
							<a href="{% url 'category_page' 'Technology' %}">Technology</a>
						</li>
						<li><a href="{% url 'category_page' 'Travel' %}">Travel</a></li>
						<li><a href="{% url 'category_page' 'Business' %}">Business</a></li>
						<li><a href="{% url 'category_page' 'Economy' %}">Economy</a></li>
						<li><a href="{% url 'category_page' 'Sports' %}">Sports</a></li>
					</ul>
				</div>
			</div>

			<div class="footer-right">
				{% if not user.is_authenticated %}
				<section class="subscribe-section">
					<form action="{% url 'subscribe' %}" method="post">
						<div class="subscribe-form">
							{% csrf_token %}
							<div class="subscribe-message">
								<p class="subscribe-text">Weekly Newsletter</p>
								<p class="subscribe-text-info">
									Get blog articles and offers via email
								</p>
							</div>
							<div class="subscribe-input">
								<input
									id="name"
									name="name"
									class="name-input"
									placeholder="Your Name"
									autocomplete="name"
								/>
							</div>
							<div class="subscribe-input">
								<input
									id="email"
									name="email"
									type="email"
									class="email-input"
									placeholder="Email address"
									autocomplete="email"
								/>
							</div>
							<div class="subscribe-button">
								<button type="submit" class="subscribe-submit">
									Subscribe
									<i class="submit-icon"></i>
								</button>
							</div>
						</div>
					</form>
				</section>
				{% endif %}
			</div>
		</section>
		<hr class="separator" />
		<section class="footer-section-2">
			<div class="logo-section">
				<img src="{% static 'img/logo.svg' %}" alt="" />
				<div class="meta-info">
					<p class="footer-company-name">Meta<span>Blog</span></p>
					<p class="footer-rights">
						© {{author_name }} {% now "Y" %}. All Rights Reserved.
					</p>
				</div>
			</div>
			<div class="footer-links">
				<a href="/terms-of-use">Terms of Use</a>
				<p>|</p>
				<a href="/privacy-policy">Privacy Policy</a>
				<p>|</p>
				<a href="/cookie-policy">Cookie Policy</a>
			</div>
		</section>
	</div>
</footer>

page/blog/templates/partials/header.html
{% load static %}
<header class="page-header">
	<div class="header-container">
		<div class="logo-container">
			<a href="{% url 'home_page' %}" class="logo"
				><img
					src="{% static 'img/logo-name.svg' %}"
					alt="Logo Blog"
					width="150"
					height="auto"
					loading="lazy"
			/></a>
		</div>
		<div class="menu-wrapper">
			<button
				type="button"
				class="mobile-button"
				aria-expanded="false"
				aria-controls="menu-container"
				data-menu-button
			>
				<img
					class="menu-icons icon-close"
					aria-label="Mobile switcher"
					src="{% static '/img/ico/close.svg' %}"
					alt="Close icon"
					style="width: 40px; height: 40px"
				/>
				<img
					class="menu-icons icon-burger"
					aria-label="Mobile switcher"
					src="{% static '/img/ico/burger.svg' %}"
					alt="Burger icon"
					style="width: 40px; height: 40px"
				/>
			</button>

			<div class="menu-container" id="menu-container" data-menu>
				<nav class="main-navigation">
					<ul class="menu-list">
						<li class="menu-item">
							<a href="{% url 'home_page' %}" class="menu-link current">Home</a>
						</li>
						<li class="menu-item">
							<a href="{% url 'single_post_page' %}" class="menu-link"
								>Single Post</a
							>
						</li>
						<li class="menu-item">
							<a href="{% url 'pages_page' %}" class="menu-link">Pages</a>
						</li>
						<li class="menu-item">
							<a href="{% url 'about_page' %}" class="menu-link">About</a>
						</li>
						<li class="menu-item">
							<a href="{% url 'contact_page' %}" class="menu-link">Contact</a>
						</li>
					</ul>
				</nav>
				<div class="is-hidden">
					{% if user.is_authenticated %}
					<div class="button-item">
						<a href="{% url 'logout' %}" class="button-link">Logout</a>
					</div>
					{% if not '/profile-view/' in request.path %}
					<div class="button-item">
						<a href="{% url 'profile-view' %}" class="button-link">Profile</a>
					</div>
					{% endif %} {% else %}
					<div class="button-item">
						<a href="{% url 'login' %}" class="button-link">Login</a>
					</div>

					<div class="button-item">
						<a href="{% url 'registration' %}" class="button-link"
							>Registration</a
						>
					</div>
					{% endif %}
				</div>
				<div class="search-form">
					<form method="get" action="{% url 'article_search' %}">
						{{ search_form.query.label_tag }}
						<div class="search-icon-container">
							<input
								name="query"
								type="text"
								placeholder="Search"
								class="search-input"
							/>
							<img
								src="{% static 'img/magnifying-glass-solid.svg' %}"
								alt="Search Icon"
								class="img-search-icon"
							/>
						</div>
					</form>
				</div>

				<!-- -------------------------------------------------------- -->
			</div>
			<div class="user-actions">
				{% if user.is_authenticated %}
				<div class="button-item">
					<a href="{% url 'logout' %}" class="button-link">Logout</a>
				</div>
				{% if not '/profile-view/' in request.path %}
				<div class="button-item">
					<a href="{% url 'profile-view' %}" class="button-link">Profile</a>
				</div>
				{% endif %} {% else %}
				<div class="button-item">
					<a href="{% url 'login' %}" class="button-link">Login</a>
				</div>

				<div class="button-item">
					<a href="{% url 'registration' %}" class="button-link"
						>Registration</a
					>
				</div>
				{% endif %}
			</div>
		</div>
	</div>
</header>

page/blog/templates/partials/hero_author.html
{% load static %}
<section class="hero-author">
	<div class="hero-author-info">
		<div class="hero-author-avatar-container">
			<img
				class="hero-author-avatar"
				src="{{ articles.0.author.profile.image.url }}"
				alt="{{ articles.0.author.username }}"
			/>
			<p class="hero-author-username">{{ author }}</p>
		</div>
		<div class="hero-author-bio">
			<p class="hero-author-bio-text">{{ articles.0.author.profile.bio }}</p>
		</div>
		<div class="hero-author-social">
			<ul class="hero-author-social-list">
				{% if articles.0.author.profile.twitter_url %}
				<li class="hero-author-social-item">
					<a href="{{ articles.0.author.profile.twitter_url }}"
						><img
							class="hero-author-social-img"
							src="{% static 'img/button_twitter.svg' %}"
							alt="Twitter"
					/></a>
				</li>
				{% endif %}
				{% if articles.0.author.profile.instagram_url %}
				<li class="hero-author-social-item">
					<a href="{{ articles.0.author.profile.instagram_url }}"
						><img
							class="hero-author-social-img"
							src="{% static 'img/button_instagram.svg' %}"
							alt="Instagram"
					/></a>
				</li>
				{% endif %}
				{% if articles.0.author.profile.facebook_url %}
				<li class="hero-author-social-item">
					<a href="{{ articles.0.author.profile.facebook_url }}">
						<img
							class="hero-author-social-img"
							src="{% static 'img/button_facebook.svg' %}"
							alt="Facebook"
						/>
					</a>
				</li>
			{% endif %}
				<li class="hero-author-social-item">
					<a href="{{ articles.0.author.profile.youtube_url }}"
						><img
							class="hero-author-social-img"
							src="{% static 'img/button_youtube.svg' %}"
							alt="YouTube"
					/></a>
				</li>
			</ul>
		</div>
	</div>
</section>

page/blog/templates/partials/hero_form.html
{% load static %}
<nav class="profile-navigation" id="navbar-main">
	<div class="nav-container">
		<a class="profile-link" href="#" target="_blank">{{ page_title }}</a>
		<ul class="profile-menu">
			<li class="profile-dropdown">
				{% if show_link %}
				<a
					class="dropdown-toggle"
					href="#"
					role="button"
					data-toggle="dropdown"
					aria-haspopup="true"
					aria-expanded="false"
				>
					<div class="profile-info">
						<span class="profile-img">
							<img
								alt="Image placeholder"
								src="{{ user.profile.image.url }}"
							/>
						</span>
						<div class="profile-username">
							<span class="username">{{ user.username }}</span>
						</div>
					</div>
				</a>
				{% endif %}
				<div class="dropdown-menu">
					<div class="dropdown-content"></div>
				</div>
			</li>
		</ul>
	</div>
</nav>
<div
	class="profile-banner"
	style="
		min-height: 600px;
		background-image: url({% static 'img/images/luca-bravo-XJXWbfSo2f0-unsplash.jpg' %});
		background-size: cover;
		background-position: center top;
	"
>
	<span class="banner-overlay"></span>
	<div class="profile-info-container">
		<h1 class="profile-greeting">Hello {{ user.username }}</h1>
		<p class="profile-description">{{ page_description }}</p>
		{% if show_link %}
		<a href="{% url 'profile' %}" class="profile-edit-link">Edit profile</a>
		{% endif %}
	</div>
</div>

page/blog/templates/partials/hero_post.html
{% load static %}
<section class="hero-container">
	<img
		src="{% static 'img/home_page_bg.jpg' %}"
		alt="Background Image"
		class="background-image"
	/>
	<div class="hero-article-details">
		<div class="hero-article-category">
			<a href="{{ specific_article.get_category_url }}"
				>{{ specific_article.category }}</a
			>
		</div>
		<h2 class="hero-article-title">
			<a href="{{ specific_article.get_absolute_url }}"
				>{{ specific_article.title | safe }}</a
			>
		</h2>
		<div class="hero-article-footer">
			<div class="hero-article-footer-items">
				<a
					class="hero-article-footer-author"
					href="{{ specific_article.get_author_url }}"
					><img
						class="hero-article-footer-avatar"
						src="{{ specific_article.author.profile.image.url }}"
						alt="{{ article.author.username }}"
					/>
					{{ specific_article.author }}</a
				>
				<p>{{ specific_article.pubdate|date:"F j, Y" }}</p>
			</div>
		</div>
	</div>
</section>

page/blog/templates/partials/login.html
{% extends 'base.html' %} {% load static %} {% load i18n %}
<!-- ------------------------------------------------------------------------------------- -->
{% block title %}{{ author_name }}: {{ article.title | safe }} {% endblock %}
<!-- ------------------------------------------------------------------------------------- -->

<!-- ------------------------------------------------------------------------------------- -->

{% block content %}
<div class="user-profile" id="user-profile-edit">
	{% include 'partials/hero_form.html' %}
</div>

<div class="form-login-container">
	<h2 class="form-login-title">LOGIN</h2>
	<form method="post" class="form-login-field">
		{% csrf_token %} {{ form.as_p }}
		<button class="form-login-button" type="submit">Login</button>
	</form>
</div>
<script src="{% static 'js/login.js' %}"></script>

{% endblock %}

page/blog/templates/partials/modal.html
<div class="lightbox js-lightbox">
	<div class="lightbox-overlay"></div>
	<div class="lightbox-content">
		<img class="lightbox-image" src="" alt="" />
	</div>
	<button
		type="button"
		class="lightbox-button"
		data-action="close-lightbox"
	></button>
</div>

page/blog/templates/partials/newsletter.html
{% extends "base.html" %} {% block content %}
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_subject">Subject</label>
      <input type="text" class="form-control" id="id_subject" name="subject" />
    </div>
    <div class="form-group">
      <label for="id_message">Message</label>
      <textarea class="form-control" id="id_message" name="message"></textarea>
    </div>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Send</button>
    </div>
  </form>
</div>
{% endblock content %}

page/blog/templates/partials/pagination.html
<div class="pagination-container">
  {% if page.has_previous %}
  <a href="?page={{ page.previous_page_number }}" class="pagination-button"
    >Previous</a
  >
  {% else %}
  <span class="pagination-button-disabled">Previous</span>
  {% endif %} {% for i in page.paginator.page_range %} {% if page.number == i %}
  <span class="pagination-current">{{ i }}</span>
  {% else %}
  <a href="?page={{ i }}" class="pagination-button">{{ i }}</a>
  {% endif %} {% endfor %} {% if page.has_next %}
  <a href="?page={{ page.next_page_number }}" class="pagination-button">Next</a>
  {% else %}
  <span class="pagination-button-disabled">Next</span>
  {% endif %}
</div>

page/blog/templates/partials/profile_edit.html
{% extends "base.html" %} {% load static%} {% block content %}
<div class="user-profile" id="user-profile-edit">
	{% include 'partials/hero_form.html' %}
</div>

<div class="content-profile">
	<div class="profile-user">
		<div class="profile-image">
			<img class="user-img" src="{{ user.profile.image.url }}" />
		</div>
		<div class="user-details">
			<h2 class="user-name">{{ user.username }}</h2>
			<p class="user-email">{{ user.email }}</p>
		</div>
	</div>
	<div class="form-profile-header">
	</div>
	<!-- FORM HERE -->
	<form class="form-profile" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<fieldset class="form-section-profile">
			<legend class="section-title-profile">Profile Info</legend>
			{{ u_form }}
			<!-- User form -->
			{{ p_form }}
			<!-- Profile form -->
			<div class="form-actions-profile">
				<button class="btn-update-profile" type="submit">Update</button>
				<button class="btn-update-profile" id="btn-cancel-profile" type="button">Cancel</button>
			</div>
		</fieldset>
	</form>
</div>
<script src="{% static 'js/profile.js' %}"></script>
{% endblock content %}